#!/bin/bash
set -e

OPENRC=$1
TAG=$2
SSH_KEY_FILE=$3

if [ $# -ne 3 ]; then
    echo "Usage: cleanup <openrc> <tag> <ssh_key>"
    exit 1
fi

source "$OPENRC"
echo "[*] Cleaning up all resources tagged with $TAG..."
echo "[*] Deleting keypair..."
openstack keypair delete $TAG-keypair

python3 scripts/cloud_utils.py cleanup $TAG $TAG-keypair $SSH_KEY_FILE
